server:
  port: 9999
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.15:3306/test?useSLL=false&serverTimezone=GMT%2B8
    username: root
    password: dahouqin@2020
  redis:
    database: 0
    host: 192.168.1.179
    port: 6379
    timeout: 300
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dreamless.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0